name: restaurant
description: "Multi-Tenant Restaurant Management SaaS Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.0.3

  # Backend (Firebase)
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  cloud_functions: ^6.0.1

  # UI
  google_fonts: ^6.2.1
  responsive_framework: ^1.5.1
  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  printing: ^5.14.2
  pdf: ^3.11.3
  intl: ^0.20.2
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
